/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface HeadsetBattery {
  'batteryLevel' : bigint,
  'lastUpdated' : bigint,
  'deviceId' : string,
}
export interface IntakeState {
  'mood' : [] | [Mood],
  'vibe' : [] | [Vibe],
  'language' : Language,
  'anxietyLevel' : bigint,
  'profile' : [] | [ProfileType],
}
export type Language = { 'tamil' : null } |
  { 'hindi' : null } |
  { 'kannada' : null } |
  { 'telugu' : null } |
  { 'english' : null };
export type MediaProvider = { 'youtubeMusic' : null } |
  { 'spotify' : null } |
  { 'appleMusic' : null };
export type Mood = { 'distract' : null } |
  { 'relax' : null } |
  { 'listen' : null };
export type OTTProvider = { 'netflix' : null } |
  { 'hotstar' : null } |
  { 'primeVideo' : null } |
  { 'youtube' : null };
export interface OTTSession {
  'provider' : OTTProvider,
  'lastTitle' : [] | [string],
  'timestamp' : bigint,
}
export interface Playlist {
  'id' : string,
  'url' : string,
  'title' : string,
  'provider' : MediaProvider,
  'premiumFlag' : SubscriptionFlag,
  'language' : Language,
  'category' : PlaylistCategory,
}
export type PlaylistCategory = { 'bollywoodClassics' : null } |
  { 'upbeat' : null } |
  { 'kannadaHits' : null };
export type ProfileType = { 'kid' : null } |
  { 'adult' : null } |
  { 'teen' : null } |
  { 'senior' : null };
export type SubscriptionFlag = { 'premium' : null } |
  { 'free' : null };
export interface UserProfile {
  'name' : string,
  'profileType' : [] | [ProfileType],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Vibe = { 'focus' : null } |
  { 'nurture' : null } |
  { 'escape' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'banProviders' : ActorMethod<[Array<MediaProvider>], undefined>,
  'createPlaylist' : ActorMethod<[Playlist], undefined>,
  'deletePlaylist' : ActorMethod<[string], undefined>,
  'getActiveProviders' : ActorMethod<[], Array<MediaProvider>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEnabledOTTProviders' : ActorMethod<[], Array<OTTProvider>>,
  'getHeadsetBatteries' : ActorMethod<[], Array<HeadsetBattery>>,
  'getHeadsetBattery' : ActorMethod<[string], [] | [HeadsetBattery]>,
  'getIntakeState' : ActorMethod<[], [] | [IntakeState]>,
  'getOTTSession' : ActorMethod<[], [] | [OTTSession]>,
  'getPlaylistsForLanguage' : ActorMethod<[Language], Array<Playlist>>,
  'getRegionalAndExtraCategories' : ActorMethod<[], Array<Playlist>>,
  'getSafeVolumeCap' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isPremiumEnabled' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveIntakeState' : ActorMethod<[IntakeState], undefined>,
  'saveOTTSession' : ActorMethod<[OTTSession], undefined>,
  'setEnabledOTTProviders' : ActorMethod<[Array<OTTProvider>], undefined>,
  'setPremiumEnabled' : ActorMethod<[boolean], undefined>,
  'updateHeadsetBattery' : ActorMethod<[string, bigint, bigint], undefined>,
  'updateStaffPasscode' : ActorMethod<[string], undefined>,
  'updateVolumeCap' : ActorMethod<[bigint], undefined>,
  'verifyStaffPasscode' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];