/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MediaProvider = IDL.Variant({
  'youtubeMusic' : IDL.Null,
  'spotify' : IDL.Null,
  'appleMusic' : IDL.Null,
});
export const SubscriptionFlag = IDL.Variant({
  'premium' : IDL.Null,
  'free' : IDL.Null,
});
export const Language = IDL.Variant({
  'tamil' : IDL.Null,
  'hindi' : IDL.Null,
  'kannada' : IDL.Null,
  'telugu' : IDL.Null,
  'english' : IDL.Null,
});
export const PlaylistCategory = IDL.Variant({
  'bollywoodClassics' : IDL.Null,
  'upbeat' : IDL.Null,
  'kannadaHits' : IDL.Null,
});
export const Playlist = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'provider' : MediaProvider,
  'premiumFlag' : SubscriptionFlag,
  'language' : Language,
  'category' : PlaylistCategory,
});
export const ProfileType = IDL.Variant({
  'kid' : IDL.Null,
  'adult' : IDL.Null,
  'teen' : IDL.Null,
  'senior' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'profileType' : IDL.Opt(ProfileType),
});
export const OTTProvider = IDL.Variant({
  'netflix' : IDL.Null,
  'hotstar' : IDL.Null,
  'primeVideo' : IDL.Null,
  'youtube' : IDL.Null,
});
export const HeadsetBattery = IDL.Record({
  'batteryLevel' : IDL.Nat,
  'lastUpdated' : IDL.Nat,
  'deviceId' : IDL.Text,
});
export const Mood = IDL.Variant({
  'distract' : IDL.Null,
  'relax' : IDL.Null,
  'listen' : IDL.Null,
});
export const Vibe = IDL.Variant({
  'focus' : IDL.Null,
  'nurture' : IDL.Null,
  'escape' : IDL.Null,
});
export const IntakeState = IDL.Record({
  'mood' : IDL.Opt(Mood),
  'vibe' : IDL.Opt(Vibe),
  'language' : Language,
  'anxietyLevel' : IDL.Nat,
  'profile' : IDL.Opt(ProfileType),
});
export const OTTSession = IDL.Record({
  'provider' : OTTProvider,
  'lastTitle' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'banProviders' : IDL.Func([IDL.Vec(MediaProvider)], [], []),
  'createPlaylist' : IDL.Func([Playlist], [], []),
  'deletePlaylist' : IDL.Func([IDL.Text], [], []),
  'getActiveProviders' : IDL.Func([], [IDL.Vec(MediaProvider)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEnabledOTTProviders' : IDL.Func([], [IDL.Vec(OTTProvider)], ['query']),
  'getHeadsetBatteries' : IDL.Func([], [IDL.Vec(HeadsetBattery)], ['query']),
  'getHeadsetBattery' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(HeadsetBattery)],
      ['query'],
    ),
  'getIntakeState' : IDL.Func([], [IDL.Opt(IntakeState)], ['query']),
  'getOTTSession' : IDL.Func([], [IDL.Opt(OTTSession)], ['query']),
  'getPlaylistsForLanguage' : IDL.Func(
      [Language],
      [IDL.Vec(Playlist)],
      ['query'],
    ),
  'getRegionalAndExtraCategories' : IDL.Func(
      [],
      [IDL.Vec(Playlist)],
      ['query'],
    ),
  'getSafeVolumeCap' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isPremiumEnabled' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveIntakeState' : IDL.Func([IntakeState], [], []),
  'saveOTTSession' : IDL.Func([OTTSession], [], []),
  'setEnabledOTTProviders' : IDL.Func([IDL.Vec(OTTProvider)], [], []),
  'setPremiumEnabled' : IDL.Func([IDL.Bool], [], []),
  'updateHeadsetBattery' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'updateStaffPasscode' : IDL.Func([IDL.Text], [], []),
  'updateVolumeCap' : IDL.Func([IDL.Nat], [], []),
  'verifyStaffPasscode' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MediaProvider = IDL.Variant({
    'youtubeMusic' : IDL.Null,
    'spotify' : IDL.Null,
    'appleMusic' : IDL.Null,
  });
  const SubscriptionFlag = IDL.Variant({
    'premium' : IDL.Null,
    'free' : IDL.Null,
  });
  const Language = IDL.Variant({
    'tamil' : IDL.Null,
    'hindi' : IDL.Null,
    'kannada' : IDL.Null,
    'telugu' : IDL.Null,
    'english' : IDL.Null,
  });
  const PlaylistCategory = IDL.Variant({
    'bollywoodClassics' : IDL.Null,
    'upbeat' : IDL.Null,
    'kannadaHits' : IDL.Null,
  });
  const Playlist = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'provider' : MediaProvider,
    'premiumFlag' : SubscriptionFlag,
    'language' : Language,
    'category' : PlaylistCategory,
  });
  const ProfileType = IDL.Variant({
    'kid' : IDL.Null,
    'adult' : IDL.Null,
    'teen' : IDL.Null,
    'senior' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'profileType' : IDL.Opt(ProfileType),
  });
  const OTTProvider = IDL.Variant({
    'netflix' : IDL.Null,
    'hotstar' : IDL.Null,
    'primeVideo' : IDL.Null,
    'youtube' : IDL.Null,
  });
  const HeadsetBattery = IDL.Record({
    'batteryLevel' : IDL.Nat,
    'lastUpdated' : IDL.Nat,
    'deviceId' : IDL.Text,
  });
  const Mood = IDL.Variant({
    'distract' : IDL.Null,
    'relax' : IDL.Null,
    'listen' : IDL.Null,
  });
  const Vibe = IDL.Variant({
    'focus' : IDL.Null,
    'nurture' : IDL.Null,
    'escape' : IDL.Null,
  });
  const IntakeState = IDL.Record({
    'mood' : IDL.Opt(Mood),
    'vibe' : IDL.Opt(Vibe),
    'language' : Language,
    'anxietyLevel' : IDL.Nat,
    'profile' : IDL.Opt(ProfileType),
  });
  const OTTSession = IDL.Record({
    'provider' : OTTProvider,
    'lastTitle' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'banProviders' : IDL.Func([IDL.Vec(MediaProvider)], [], []),
    'createPlaylist' : IDL.Func([Playlist], [], []),
    'deletePlaylist' : IDL.Func([IDL.Text], [], []),
    'getActiveProviders' : IDL.Func([], [IDL.Vec(MediaProvider)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEnabledOTTProviders' : IDL.Func([], [IDL.Vec(OTTProvider)], ['query']),
    'getHeadsetBatteries' : IDL.Func([], [IDL.Vec(HeadsetBattery)], ['query']),
    'getHeadsetBattery' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(HeadsetBattery)],
        ['query'],
      ),
    'getIntakeState' : IDL.Func([], [IDL.Opt(IntakeState)], ['query']),
    'getOTTSession' : IDL.Func([], [IDL.Opt(OTTSession)], ['query']),
    'getPlaylistsForLanguage' : IDL.Func(
        [Language],
        [IDL.Vec(Playlist)],
        ['query'],
      ),
    'getRegionalAndExtraCategories' : IDL.Func(
        [],
        [IDL.Vec(Playlist)],
        ['query'],
      ),
    'getSafeVolumeCap' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isPremiumEnabled' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveIntakeState' : IDL.Func([IntakeState], [], []),
    'saveOTTSession' : IDL.Func([OTTSession], [], []),
    'setEnabledOTTProviders' : IDL.Func([IDL.Vec(OTTProvider)], [], []),
    'setPremiumEnabled' : IDL.Func([IDL.Bool], [], []),
    'updateHeadsetBattery' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'updateStaffPasscode' : IDL.Func([IDL.Text], [], []),
    'updateVolumeCap' : IDL.Func([IDL.Nat], [], []),
    'verifyStaffPasscode' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };