/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface HeadsetBattery {
    batteryLevel: bigint;
    lastUpdated: bigint;
    deviceId: string;
}
export interface Playlist {
    id: string;
    url: string;
    title: string;
    provider: MediaProvider;
    premiumFlag: SubscriptionFlag;
    language: Language;
    category: PlaylistCategory;
}
export interface OTTSession {
    provider: OTTProvider;
    lastTitle?: string;
    timestamp: bigint;
}
export interface IntakeState {
    mood?: Mood;
    vibe?: Vibe;
    language: Language;
    anxietyLevel: bigint;
    profile?: ProfileType;
}
export interface UserProfile {
    name: string;
    profileType?: ProfileType;
}
export enum Language {
    tamil = "tamil",
    hindi = "hindi",
    kannada = "kannada",
    telugu = "telugu",
    english = "english"
}
export enum MediaProvider {
    youtubeMusic = "youtubeMusic",
    spotify = "spotify",
    appleMusic = "appleMusic"
}
export enum Mood {
    distract = "distract",
    relax = "relax",
    listen = "listen"
}
export enum OTTProvider {
    netflix = "netflix",
    hotstar = "hotstar",
    primeVideo = "primeVideo",
    youtube = "youtube"
}
export enum PlaylistCategory {
    bollywoodClassics = "bollywoodClassics",
    upbeat = "upbeat",
    kannadaHits = "kannadaHits"
}
export enum ProfileType {
    kid = "kid",
    adult = "adult",
    teen = "teen",
    senior = "senior"
}
export enum SubscriptionFlag {
    premium = "premium",
    free = "free"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Vibe {
    focus = "focus",
    nurture = "nurture",
    escape = "escape"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    banProviders(providers: Array<MediaProvider>): Promise<void>;
    createPlaylist(playlist: Playlist): Promise<void>;
    deletePlaylist(playlistId: string): Promise<void>;
    getActiveProviders(): Promise<Array<MediaProvider>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEnabledOTTProviders(): Promise<Array<OTTProvider>>;
    getHeadsetBatteries(): Promise<Array<HeadsetBattery>>;
    getHeadsetBattery(deviceId: string): Promise<HeadsetBattery | null>;
    getIntakeState(): Promise<IntakeState | null>;
    getOTTSession(): Promise<OTTSession | null>;
    getPlaylistsForLanguage(language: Language): Promise<Array<Playlist>>;
    getRegionalAndExtraCategories(): Promise<Array<Playlist>>;
    getSafeVolumeCap(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isPremiumEnabled(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveIntakeState(state: IntakeState): Promise<void>;
    saveOTTSession(session: OTTSession): Promise<void>;
    setEnabledOTTProviders(providers: Array<OTTProvider>): Promise<void>;
    setPremiumEnabled(enabled: boolean): Promise<void>;
    updateHeadsetBattery(deviceId: string, batteryLevel: bigint, timestamp: bigint): Promise<void>;
    updateStaffPasscode(newPasscode: string): Promise<void>;
    updateVolumeCap(cap: bigint): Promise<void>;
    verifyStaffPasscode(passcode: string): Promise<boolean>;
}
import type { HeadsetBattery as _HeadsetBattery, IntakeState as _IntakeState, Language as _Language, MediaProvider as _MediaProvider, Mood as _Mood, OTTProvider as _OTTProvider, OTTSession as _OTTSession, Playlist as _Playlist, PlaylistCategory as _PlaylistCategory, ProfileType as _ProfileType, SubscriptionFlag as _SubscriptionFlag, UserProfile as _UserProfile, UserRole as _UserRole, Vibe as _Vibe } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async banProviders(arg0: Array<MediaProvider>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.banProviders(to_candid_vec_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.banProviders(to_candid_vec_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createPlaylist(arg0: Playlist): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlaylist(to_candid_Playlist_n6(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlaylist(to_candid_Playlist_n6(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deletePlaylist(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePlaylist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePlaylist(arg0);
            return result;
        }
    }
    async getActiveProviders(): Promise<Array<MediaProvider>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveProviders();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveProviders();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEnabledOTTProviders(): Promise<Array<OTTProvider>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnabledOTTProviders();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnabledOTTProviders();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHeadsetBatteries(): Promise<Array<HeadsetBattery>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHeadsetBatteries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHeadsetBatteries();
            return result;
        }
    }
    async getHeadsetBattery(arg0: string): Promise<HeadsetBattery | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHeadsetBattery(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHeadsetBattery(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIntakeState(): Promise<IntakeState | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getIntakeState();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIntakeState();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOTTSession(): Promise<OTTSession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOTTSession();
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOTTSession();
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlaylistsForLanguage(arg0: Language): Promise<Array<Playlist>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlaylistsForLanguage(to_candid_Language_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlaylistsForLanguage(to_candid_Language_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRegionalAndExtraCategories(): Promise<Array<Playlist>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegionalAndExtraCategories();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegionalAndExtraCategories();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSafeVolumeCap(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getSafeVolumeCap();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSafeVolumeCap();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isPremiumEnabled(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isPremiumEnabled();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isPremiumEnabled();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n51(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n51(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveIntakeState(arg0: IntakeState): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveIntakeState(to_candid_IntakeState_n55(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveIntakeState(to_candid_IntakeState_n55(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveOTTSession(arg0: OTTSession): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveOTTSession(to_candid_OTTSession_n61(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveOTTSession(to_candid_OTTSession_n61(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setEnabledOTTProviders(arg0: Array<OTTProvider>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setEnabledOTTProviders(to_candid_vec_n65(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setEnabledOTTProviders(to_candid_vec_n65(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setPremiumEnabled(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPremiumEnabled(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPremiumEnabled(arg0);
            return result;
        }
    }
    async updateHeadsetBattery(arg0: string, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHeadsetBattery(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHeadsetBattery(arg0, arg1, arg2);
            return result;
        }
    }
    async updateStaffPasscode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStaffPasscode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStaffPasscode(arg0);
            return result;
        }
    }
    async updateVolumeCap(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVolumeCap(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVolumeCap(arg0);
            return result;
        }
    }
    async verifyStaffPasscode(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyStaffPasscode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyStaffPasscode(arg0);
            return result;
        }
    }
}
function from_candid_IntakeState_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IntakeState): IntakeState {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Language_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Language): Language {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_MediaProvider_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MediaProvider): MediaProvider {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Mood_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Mood): Mood {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_OTTProvider_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OTTProvider): OTTProvider {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_OTTSession_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OTTSession): OTTSession {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_PlaylistCategory_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlaylistCategory): PlaylistCategory {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_Playlist_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Playlist): Playlist {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_ProfileType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProfileType): ProfileType {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionFlag_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionFlag): SubscriptionFlag {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Vibe_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Vibe): Vibe {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProfileType]): ProfileType | null {
    return value.length === 0 ? null : from_candid_ProfileType_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HeadsetBattery]): HeadsetBattery | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_IntakeState]): IntakeState | null {
    return value.length === 0 ? null : from_candid_IntakeState_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Mood]): Mood | null {
    return value.length === 0 ? null : from_candid_Mood_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Vibe]): Vibe | null {
    return value.length === 0 ? null : from_candid_Vibe_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OTTSession]): OTTSession | null {
    return value.length === 0 ? null : from_candid_OTTSession_n41(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    profileType: [] | [_ProfileType];
}): {
    name: string;
    profileType?: ProfileType;
} {
    return {
        name: value.name,
        profileType: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.profileType))
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mood: [] | [_Mood];
    vibe: [] | [_Vibe];
    language: _Language;
    anxietyLevel: bigint;
    profile: [] | [_ProfileType];
}): {
    mood?: Mood;
    vibe?: Vibe;
    language: Language;
    anxietyLevel: bigint;
    profile?: ProfileType;
} {
    return {
        mood: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.mood)),
        vibe: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.vibe)),
        language: from_candid_Language_n38(_uploadFile, _downloadFile, value.language),
        anxietyLevel: value.anxietyLevel,
        profile: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.profile))
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    provider: _OTTProvider;
    lastTitle: [] | [string];
    timestamp: bigint;
}): {
    provider: OTTProvider;
    lastTitle?: string;
    timestamp: bigint;
} {
    return {
        provider: from_candid_OTTProvider_n26(_uploadFile, _downloadFile, value.provider),
        lastTitle: record_opt_to_undefined(from_candid_opt_n43(_uploadFile, _downloadFile, value.lastTitle)),
        timestamp: value.timestamp
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    url: string;
    title: string;
    provider: _MediaProvider;
    premiumFlag: _SubscriptionFlag;
    language: _Language;
    category: _PlaylistCategory;
}): {
    id: string;
    url: string;
    title: string;
    provider: MediaProvider;
    premiumFlag: SubscriptionFlag;
    language: Language;
    category: PlaylistCategory;
} {
    return {
        id: value.id,
        url: value.url,
        title: value.title,
        provider: from_candid_MediaProvider_n15(_uploadFile, _downloadFile, value.provider),
        premiumFlag: from_candid_SubscriptionFlag_n47(_uploadFile, _downloadFile, value.premiumFlag),
        language: from_candid_Language_n38(_uploadFile, _downloadFile, value.language),
        category: from_candid_PlaylistCategory_n49(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    youtubeMusic: null;
} | {
    spotify: null;
} | {
    appleMusic: null;
}): MediaProvider {
    return "youtubeMusic" in value ? MediaProvider.youtubeMusic : "spotify" in value ? MediaProvider.spotify : "appleMusic" in value ? MediaProvider.appleMusic : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    kid: null;
} | {
    adult: null;
} | {
    teen: null;
} | {
    senior: null;
}): ProfileType {
    return "kid" in value ? ProfileType.kid : "adult" in value ? ProfileType.adult : "teen" in value ? ProfileType.teen : "senior" in value ? ProfileType.senior : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    netflix: null;
} | {
    hotstar: null;
} | {
    primeVideo: null;
} | {
    youtube: null;
}): OTTProvider {
    return "netflix" in value ? OTTProvider.netflix : "hotstar" in value ? OTTProvider.hotstar : "primeVideo" in value ? OTTProvider.primeVideo : "youtube" in value ? OTTProvider.youtube : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    distract: null;
} | {
    relax: null;
} | {
    listen: null;
}): Mood {
    return "distract" in value ? Mood.distract : "relax" in value ? Mood.relax : "listen" in value ? Mood.listen : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    focus: null;
} | {
    nurture: null;
} | {
    escape: null;
}): Vibe {
    return "focus" in value ? Vibe.focus : "nurture" in value ? Vibe.nurture : "escape" in value ? Vibe.escape : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tamil: null;
} | {
    hindi: null;
} | {
    kannada: null;
} | {
    telugu: null;
} | {
    english: null;
}): Language {
    return "tamil" in value ? Language.tamil : "hindi" in value ? Language.hindi : "kannada" in value ? Language.kannada : "telugu" in value ? Language.telugu : "english" in value ? Language.english : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    premium: null;
} | {
    free: null;
}): SubscriptionFlag {
    return "premium" in value ? SubscriptionFlag.premium : "free" in value ? SubscriptionFlag.free : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bollywoodClassics: null;
} | {
    upbeat: null;
} | {
    kannadaHits: null;
}): PlaylistCategory {
    return "bollywoodClassics" in value ? PlaylistCategory.bollywoodClassics : "upbeat" in value ? PlaylistCategory.upbeat : "kannadaHits" in value ? PlaylistCategory.kannadaHits : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MediaProvider>): Array<MediaProvider> {
    return value.map((x)=>from_candid_MediaProvider_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OTTProvider>): Array<OTTProvider> {
    return value.map((x)=>from_candid_OTTProvider_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Playlist>): Array<Playlist> {
    return value.map((x)=>from_candid_Playlist_n45(_uploadFile, _downloadFile, x));
}
function to_candid_IntakeState_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IntakeState): _IntakeState {
    return to_candid_record_n56(_uploadFile, _downloadFile, value);
}
function to_candid_Language_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): _Language {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_MediaProvider_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaProvider): _MediaProvider {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_Mood_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mood): _Mood {
    return to_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function to_candid_OTTProvider_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OTTProvider): _OTTProvider {
    return to_candid_variant_n64(_uploadFile, _downloadFile, value);
}
function to_candid_OTTSession_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OTTSession): _OTTSession {
    return to_candid_record_n62(_uploadFile, _downloadFile, value);
}
function to_candid_PlaylistCategory_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlaylistCategory): _PlaylistCategory {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_Playlist_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Playlist): _Playlist {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_ProfileType_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfileType): _ProfileType {
    return to_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionFlag_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionFlag): _SubscriptionFlag {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n52(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Vibe_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Vibe): _Vibe {
    return to_candid_variant_n60(_uploadFile, _downloadFile, value);
}
function to_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    profileType?: ProfileType;
}): {
    name: string;
    profileType: [] | [_ProfileType];
} {
    return {
        name: value.name,
        profileType: value.profileType ? candid_some(to_candid_ProfileType_n53(_uploadFile, _downloadFile, value.profileType)) : candid_none()
    };
}
function to_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mood?: Mood;
    vibe?: Vibe;
    language: Language;
    anxietyLevel: bigint;
    profile?: ProfileType;
}): {
    mood: [] | [_Mood];
    vibe: [] | [_Vibe];
    language: _Language;
    anxietyLevel: bigint;
    profile: [] | [_ProfileType];
} {
    return {
        mood: value.mood ? candid_some(to_candid_Mood_n57(_uploadFile, _downloadFile, value.mood)) : candid_none(),
        vibe: value.vibe ? candid_some(to_candid_Vibe_n59(_uploadFile, _downloadFile, value.vibe)) : candid_none(),
        language: to_candid_Language_n10(_uploadFile, _downloadFile, value.language),
        anxietyLevel: value.anxietyLevel,
        profile: value.profile ? candid_some(to_candid_ProfileType_n53(_uploadFile, _downloadFile, value.profile)) : candid_none()
    };
}
function to_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    provider: OTTProvider;
    lastTitle?: string;
    timestamp: bigint;
}): {
    provider: _OTTProvider;
    lastTitle: [] | [string];
    timestamp: bigint;
} {
    return {
        provider: to_candid_OTTProvider_n63(_uploadFile, _downloadFile, value.provider),
        lastTitle: value.lastTitle ? candid_some(value.lastTitle) : candid_none(),
        timestamp: value.timestamp
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    url: string;
    title: string;
    provider: MediaProvider;
    premiumFlag: SubscriptionFlag;
    language: Language;
    category: PlaylistCategory;
}): {
    id: string;
    url: string;
    title: string;
    provider: _MediaProvider;
    premiumFlag: _SubscriptionFlag;
    language: _Language;
    category: _PlaylistCategory;
} {
    return {
        id: value.id,
        url: value.url,
        title: value.title,
        provider: to_candid_MediaProvider_n4(_uploadFile, _downloadFile, value.provider),
        premiumFlag: to_candid_SubscriptionFlag_n8(_uploadFile, _downloadFile, value.premiumFlag),
        language: to_candid_Language_n10(_uploadFile, _downloadFile, value.language),
        category: to_candid_PlaylistCategory_n12(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): {
    tamil: null;
} | {
    hindi: null;
} | {
    kannada: null;
} | {
    telugu: null;
} | {
    english: null;
} {
    return value == Language.tamil ? {
        tamil: null
    } : value == Language.hindi ? {
        hindi: null
    } : value == Language.kannada ? {
        kannada: null
    } : value == Language.telugu ? {
        telugu: null
    } : value == Language.english ? {
        english: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlaylistCategory): {
    bollywoodClassics: null;
} | {
    upbeat: null;
} | {
    kannadaHits: null;
} {
    return value == PlaylistCategory.bollywoodClassics ? {
        bollywoodClassics: null
    } : value == PlaylistCategory.upbeat ? {
        upbeat: null
    } : value == PlaylistCategory.kannadaHits ? {
        kannadaHits: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaProvider): {
    youtubeMusic: null;
} | {
    spotify: null;
} | {
    appleMusic: null;
} {
    return value == MediaProvider.youtubeMusic ? {
        youtubeMusic: null
    } : value == MediaProvider.spotify ? {
        spotify: null
    } : value == MediaProvider.appleMusic ? {
        appleMusic: null
    } : value;
}
function to_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfileType): {
    kid: null;
} | {
    adult: null;
} | {
    teen: null;
} | {
    senior: null;
} {
    return value == ProfileType.kid ? {
        kid: null
    } : value == ProfileType.adult ? {
        adult: null
    } : value == ProfileType.teen ? {
        teen: null
    } : value == ProfileType.senior ? {
        senior: null
    } : value;
}
function to_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mood): {
    distract: null;
} | {
    relax: null;
} | {
    listen: null;
} {
    return value == Mood.distract ? {
        distract: null
    } : value == Mood.relax ? {
        relax: null
    } : value == Mood.listen ? {
        listen: null
    } : value;
}
function to_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Vibe): {
    focus: null;
} | {
    nurture: null;
} | {
    escape: null;
} {
    return value == Vibe.focus ? {
        focus: null
    } : value == Vibe.nurture ? {
        nurture: null
    } : value == Vibe.escape ? {
        escape: null
    } : value;
}
function to_candid_variant_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OTTProvider): {
    netflix: null;
} | {
    hotstar: null;
} | {
    primeVideo: null;
} | {
    youtube: null;
} {
    return value == OTTProvider.netflix ? {
        netflix: null
    } : value == OTTProvider.hotstar ? {
        hotstar: null
    } : value == OTTProvider.primeVideo ? {
        primeVideo: null
    } : value == OTTProvider.youtube ? {
        youtube: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionFlag): {
    premium: null;
} | {
    free: null;
} {
    return value == SubscriptionFlag.premium ? {
        premium: null
    } : value == SubscriptionFlag.free ? {
        free: null
    } : value;
}
function to_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<MediaProvider>): Array<_MediaProvider> {
    return value.map((x)=>to_candid_MediaProvider_n4(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<OTTProvider>): Array<_OTTProvider> {
    return value.map((x)=>to_candid_OTTProvider_n63(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
